### ISSUE TITLE
Compound orthographic forms errors

### ISSUE THREAD

**Issue by JacobLauinger** [oracc/editing#2]
I am getting errors for compound orthographic forms that I am not sure how to deal with (screen shot below). Everything looks ok to me in the individual files and in the glossary, though I am sure I am missing something ....
![screen shot 2017-12-05 at 1 26 37 pm](https://user-images.githubusercontent.com/29659861/33623744-06cd9a72-d9c0-11e7-8a8a-bc6174ff0059.png)

**Comment by lauriepearce** [comment]
I am also having issues with PSUs, perhaps not unrelated.  Until this weekend, the following was not an issue:
![screen shot 2017-12-03 at 5 12 14 pm](https://user-images.githubusercontent.com/17686699/33626537-bca2e480-d9af-11e7-89d2-0758f8a95851.png)

**Comment by JacobLauinger** [comment]
Seems to be fixed for me now.  Thanks!  I am still getting some warnings for COF's and a number of COF's that seem to be in the glossary consistently show up as new notices when I harvest and never get merged, but I have still to go through them all individually to make sure I am not doing something wrong.  If I don't find anything to correct on my end, I will flag it as a new issue.

**Comment by niekveldhuis** [comment]
Jacob,
It is useful for the discussion if you tell us what you fixed (or did it simply go away?).
The COF (Compound Orthographic Forms such as am-ma-tim for ana mātim) issue is the following (note that the @ is missing before "form" because the github editor misinterprets that as a reference to a username):
-**form am-ma-tim $(ana) mātim**
(in the mātu entry)
or
-**form am-ma-tim $ana (mātim)**
(in the ana entry)
cause errors that will actually stop the building process; change to: 
-**form am-ma-tim $(ana) $mātim**
and
-**form am-ma-tim $ana $(mātim)**
The PSU issue is still unclear - but it doesn't seem to stop oracc build.
Niek

**Comment by JacobLauinger** [comment]
The problem just went away on its own....  

Also, fwiw,  in contrast to the checker's showing, e.g., $ina (matimê), the glossary entry has always had and continues to have $ before both; e.g., $ina $(matimê). 

<img width="310" alt="screen shot 2017-12-07 at 4 37 21 pm" src="https://user-images.githubusercontent.com/29659861/33739993-18167278-db6d-11e7-9e62-4773d55fa4c5.png">

**Comment by niekveldhuis** [comment]
Interesting. That means that that is the reason why it went away for you,
but not for others (who do have single $ in their COF entries).

Niek

Niek Veldhuis
Professor of Assyriology, Department of Near Eastern Studies
Senior Fellow, Berkeley Institute of Data Science
UC Berkeley
