### ISSUE TITLE
back up files in 00lib?

### ISSUE THREAD

**Issue by JacobLauinger** [oracc/editing#3]
A quick question to see if I am supposed to have a back up file of my glossary in the 00lib directory (that is, not in 00bak).

In amarna/00lib, I have both akk-x-mbperi.glo and akk-x-mbperi.glo~

I am wondering if this backup file may be why on two occasions now when I have downloaded what I thought was the most recent glossary from the server, it turned out to be an older version?

Note: I do not have similar back up files in 00lib for my other glossaries.  I *do* have a back up file in 00lib for config.xml (config.xml~).

Not sure if this situation is the way things are supposed to be or if it might be behind some checking & rebuilding issues I've been having, so I thought I should ask ....  Thanks!

**Comment by niekveldhuis** [comment]
Jacob,
The files ending in ~ are produced by emacs/aquamacs. If you (or another editor) have opened the .glo file on the server (instead of first downloading etc.) and changed something you will create a ~ file (indeed, a backup). When you edit locally (or if your glo files are changed only by oracc software) you will not have that file.
Niek

**Comment by JacobLauinger** [comment]
Great, thank you Niek, that is very helpful.  I usually download the file and edit locally but do on occasion open it on the server when making a small change ....
