### ISSUE TITLE
unable to run oracc check or oracc build commands

### ISSUE THREAD

**Issue by JacobLauinger** [oracc/editing#6]
I've been unable to run oracc check or oracc build clean since yesterday.  Terminal just gets hung up "waiting 10 seconds."  I am also seeing "Connection refused" come up where I have not seen it before (screenshot attached).  Apologies for the bother if this is just a temporary thing as part of regular maintenance, I just thought it safer to bring it to your attention.

<img width="447" alt="screen shot 2018-01-19 at 1 18 56 pm" src="https://user-images.githubusercontent.com/29659861/35165342-f7ad0396-fd1b-11e7-86a5-6bdedd623cb2.png">

**Comment by stinney** [comment]
Thanks for the report, Jake--I've recompiled the server and it is now working.  I'll be working on other dot/hyphen issues that are affecting all projects tomorrow (Monday) morning.  I'm going to leave this issue open.  If you find this happening again just report it here.  Ordinarily, all of the Oracc steerers can fix this by logging in to the build server.  In this case, though, the problem seems to have been related to an upgrade on the machine which changed a library, necessitating recompilation.
